const CACHE='dvir-athlete-os-v9-4-source-photo-library-20260831';
const ASSETS=['./','index.html','recover.html','manifest.json','version.json','assets/icon-192.png','assets/icon-512.png','dist/app.css','dist/app.js','dist/SHA256SUMS','assets/gym-machines-2x.webp','assets/home-exercises.webp'];
self.addEventListener('install',e=>{e.waitUntil((async()=>{const c=await caches.open(CACHE);await Promise.allSettled(ASSETS.map(a=>c.add(a)));await self.skipWaiting()})())});
self.addEventListener('activate',e=>{e.waitUntil((async()=>{for(const k of await caches.keys())if(k!==CACHE)await caches.delete(k);await self.clients.claim()})())});
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method!=='GET'||u.hostname.includes('supabase.co')||u.hostname.includes('openrouter.ai')||u.hostname.includes('googleapis.com')||u.hostname.includes('openfoodfacts.org'))return;if(e.request.mode==='navigate'){e.respondWith(fetch(e.request,{cache:'no-store'}).then(r=>{const c=r.clone();caches.open(CACHE).then(x=>x.put('index.html',c));return r}).catch(()=>caches.match('index.html')));return}if(u.origin===location.origin&&(u.pathname.endsWith('/dist/app.js')||u.pathname.endsWith('/dist/app.css')||u.pathname.endsWith('/version.json')||u.pathname.endsWith('/manifest.json'))){e.respondWith(fetch(e.request,{cache:'reload'}).then(r=>{if(r.ok){const x=r.clone();caches.open(CACHE).then(k=>k.put(e.request,x))}return r}).catch(()=>caches.match(e.request)));return}e.respondWith(caches.match(e.request).then(c=>c||fetch(e.request).then(r=>{if(r.ok&&u.origin===location.origin){const x=r.clone();caches.open(CACHE).then(k=>k.put(e.request,x))}return r}).catch(()=>caches.match(e.request))))});
const DB='dvirGymSW',STORE='kv';function db(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function put(k,v){const d=await db(),t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(v,k);return new Promise(r=>t.oncomplete=r)}async function get(k){const d=await db(),t=d.transaction(STORE,'readonly'),r=t.objectStore(STORE).get(k);return new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
self.addEventListener('message',e=>{if(e.data?.type==='SET_REMINDERS')e.waitUntil((async()=>{const scope=String(e.data.scope||'guest').slice(0,100);await put('activeScope',scope);await put('reminders:'+scope,e.data.reminders||[])})());if(e.data?.type==='SET_ACTIVE_SCOPE')e.waitUntil(put('activeScope',String(e.data.scope||'guest').slice(0,100)));if(e.data?.type==='SKIP_WAITING')self.skipWaiting()});
async function checkReminders(){const scope=await get('activeScope')||'guest',rs=await get('reminders:'+scope)||[],n=new Date(),day=n.getDay(),mins=n.getHours()*60+n.getMinutes(),stamp=`${n.getFullYear()}-${n.getMonth()+1}-${n.getDate()}`,shownKey='shown:'+scope;let shown=await get(shownKey)||{};for(const r of rs){if(!r.on||!r.days?.includes(day))continue;const[h,m]=String(r.time||'00:00').split(':').map(Number),target=h*60+m;if(Math.abs(mins-target)<=12&&shown[r.id]!==stamp){await self.registration.showNotification('Dvir Gym AI',{body:r.name,icon:'assets/icon-192.png',badge:'assets/icon-192.png',tag:'dvir-local-'+scope+'-'+r.id,renotify:false,data:{url:'./'}});shown[r.id]=stamp}}await put(shownKey,shown)}
self.addEventListener('periodicsync',e=>{if(e.tag==='dvir-reminders')e.waitUntil(checkReminders())});self.addEventListener('sync',e=>{if(e.tag==='dvir-reminders')e.waitUntil(checkReminders())});
self.addEventListener('push',e=>{let d={};try{d=e.data?.json()||{}}catch{try{d={body:e.data?.text()||''}}catch{}}const title=d.title||'Dvir Gym AI',options={body:d.body||'יש לך תזכורת',icon:'assets/icon-192.png',badge:'assets/icon-192.png',tag:d.tag||'dvir-cloud-reminder',renotify:false,data:{url:d.url||'./'}};e.waitUntil(self.registration.showNotification(title,options))});
self.addEventListener('notificationclick',e=>{e.notification.close();const target=e.notification.data?.url||'./';e.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(cs=>{for(const c of cs){if('navigate'in c)c.navigate(target).catch(()=>{});if('focus'in c)return c.focus()}return clients.openWindow(target)}))});
