const CACHE='dvir-athlete-os-v6-20260814-final';
const ASSETS=['./', 'index.html', 'manifest.json', 'assets/icon-192.png', 'assets/icon-512.png', 'code/css1.txt', 'code/css2.txt', 'code/css3.txt', 'code/js1.txt', 'code/js2.txt', 'code/js3.txt', 'code/js4.txt', 'code/js5.txt', 'code/js6.txt', 'code/js7.txt', 'code/js8.txt', 'code/js9.txt', 'code/js10.txt', 'code/js11.txt', 'code/js12.txt', 'code/js13.txt', 'code/js14.txt', 'code/js15.txt', 'assets/sprite1.txt', 'assets/sprite2.txt', 'assets/sprite3.txt', 'assets/sprite4.txt', 'assets/sprite5.txt', 'assets/sprite6.txt', 'assets/sprite7.txt'];
self.addEventListener('install',e=>{e.waitUntil((async()=>{const c=await caches.open(CACHE);await Promise.allSettled(ASSETS.map(a=>c.add(a)));await self.skipWaiting()})())});
self.addEventListener('activate',e=>{e.waitUntil((async()=>{for(const k of await caches.keys())if(k!==CACHE)await caches.delete(k);await self.clients.claim()})())});
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method!=='GET'||u.hostname.includes('vercel.app'))return;if(e.request.mode==='navigate'){e.respondWith(fetch(e.request).then(r=>{const c=r.clone();caches.open(CACHE).then(x=>x.put('index.html',c));return r}).catch(()=>caches.match('index.html')));return}e.respondWith(caches.match(e.request).then(c=>c||fetch(e.request).then(r=>{if(r.ok&&u.origin===location.origin){const x=r.clone();caches.open(CACHE).then(k=>k.put(e.request,x))}return r}))) });
const DB='dvirGymSW',STORE='kv';function db(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function put(k,v){const d=await db(),t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(v,k);return new Promise(r=>t.oncomplete=r)}async function get(k){const d=await db(),t=d.transaction(STORE,'readonly'),r=t.objectStore(STORE).get(k);return new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
self.addEventListener('message',e=>{if(e.data?.type==='SET_REMINDERS')e.waitUntil(put('reminders',e.data.reminders||[]))});
async function checkReminders(){const rs=await get('reminders')||[],n=new Date(),day=n.getDay(),mins=n.getHours()*60+n.getMinutes(),stamp=`${n.getFullYear()}-${n.getMonth()+1}-${n.getDate()}`;let shown=await get('shown')||{};for(const r of rs){if(!r.on||!r.days?.includes(day))continue;const[h,m]=String(r.time||'00:00').split(':').map(Number),target=h*60+m;if(Math.abs(mins-target)<=12&&shown[r.id]!==stamp){await self.registration.showNotification('Dvir Gym AI',{body:r.name,icon:'assets/icon-192.png',badge:'assets/icon-192.png',tag:'dvir-'+r.id,renotify:false});shown[r.id]=stamp}}await put('shown',shown)}
self.addEventListener('periodicsync',e=>{if(e.tag==='dvir-reminders')e.waitUntil(checkReminders())});
self.addEventListener('sync',e=>{if(e.tag==='dvir-reminders')e.waitUntil(checkReminders())});
self.addEventListener('notificationclick',e=>{e.notification.close();e.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(cs=>{for(const c of cs)if('focus'in c)return c.focus();return clients.openWindow('./')}))});
